// src/server/db/seeds/achievements.ts

import { db } from "~/server/db/index";
import { achievements } from "~/server/db/schema";

export const defaultAchievements = [
	// ==================== DRINKING ====================
	{
		key: "spefuchs",
		name: "Spefuchs",
		description: "Trink dein erstes Bier",
		category: "drinking" as const,
		icon: "🍺",
		targetValue: 1,
		points: 10,
		rarity: "common" as const,
	},
	{
		key: "fuchs",
		name: "Fuchs",
		description: "30 Bier",
		category: "drinking" as const,
		icon: "🍻",
		targetValue: 30,
		points: 25,
		rarity: "common" as const,
	},
	{
		key: "cb",
		name: "CB",
		description: "100 Bier",
		category: "drinking" as const,
		icon: "🥃",
		targetValue: 100,
		points: 50,
		rarity: "uncommon" as const,
	},
	{
		key: "iacb",
		name: "IaCB",
		description: "300 Bier",
		category: "drinking" as const,
		icon: "🍷",
		targetValue: 300,
		points: 100,
		rarity: "rare" as const,
	},
	{
		key: "ah",
		name: "AH",
		description: "1000 Bier",
		category: "drinking" as const,
		icon: "🥂",
		targetValue: 1000,
		points: 250,
		rarity: "epic" as const,
	},
	{
		key: "aheb",
		name: "AHEB",
		description: "2000 Bier",
		category: "drinking" as const,
		icon: "👑",
		targetValue: 2000,
		points: 500,
		rarity: "legendary" as const,
	},
	{
		key: "biertasting",
		name: "Bier Tasting",
		description: "5 verschiedene Biere probieren",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 5,
		points: 10,
		rarity: "uncommon" as const,
	},
	{
		key: "kaisersflotte",
		name: "Für die Kaisers Flotte",
		description: "Eine Flasche Sekt trinken",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1,
		points: 20,
		rarity: "uncommon" as const,
	},
	{
		key: "kisteoderliste",
		name: "Kiste oder Liste",
		description: "Streich eine Kiste Bier ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1,
		points: 40,
		rarity: "uncommon" as const,
	},
	{
		key: "alkoholfrei",
		name: "Man kann auch mit Spaß Alkohol haben",
		description: "Streiche eine Kiste Alkoholfreies Bier ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1,
		points: 20,
		rarity: "uncommon" as const,
	},
	{
		key: "radler",
		name: "Sportlich schnell",
		description: "Trinke 20 Radler",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 20,
		isSecret: true,
		points: 20,
		rarity: "uncommon" as const,
	},
	{
		key: "cbesuch",
		name: "Nicht bummeln!",
		description: "Streiche 100 Bier auf CBesuch ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 100,
		points: 20,
		rarity: "common" as const,
	},
	{
		key: "cbesuch2",
		name: "Auf ein gemütliches",
		description: "Streiche 300 Bier auf CBesuch ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 300,
		points: 20,
		rarity: "common" as const,
	},
	{
		key: "cbesuch3",
		name: "Bummelelite",
		description: "Streiche 600 Bier auf CBesuch ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 600,
		points: 20,
		rarity: "common" as const,
	},
	{
		key: "cbesuch4",
		name: "Weltenbummler",
		description: "Streiche 1000 Bier auf CBesuch ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1000,
		points: 20,
		rarity: "legendary" as const,
	},

	// ==================== DRINKING SPECIAL ====================
	{
		key: "helleseite",
		name: "Die helle Seite der Macht",
		description: "Hab 50 Oetti Hell mehr als Pils getrunken",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 10,
		isSecret: true,
		points: 100,
		rarity: "rare" as const,
	},
	{
		key: "dunkleseite",
		name: "Die dunkle Seite der Macht",
		description: "Hab 50 Oetti Pils mehr als Hell getrunken",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 10,
		isSecret: true,
		points: 100,
		rarity: "rare" as const,
	},
	{
		key: "avatar",
		name: "Der Avatarzustand",
		description:
			"Hab mehrs als 100 Bier getrunken und weder Pils noch Hell dominiert",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 100,
		isSecret: true,
		points: 1000,
		rarity: "legendary" as const,
	},

	// ==================== GAMES ====================

	{
		key: "perfektewoche",
		name: "Perfekte Woche",
		description: "Jeden Tag ein Bierjungen in einer Woche",
		category: "games" as const,
		icon: "🎓",
		targetValue: 7,
		points: 50,
		rarity: "rare" as const,
	},
	{
		key: "deutschland",
		name: "Deutschland am Tresen verteidigt",
		description: "Trinke ein Bierjungen am 3. Oktober",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1,
		isSecret: true,
		points: 50,
		rarity: "rare" as const,
	},

	{
		key: "tierlunge",
		name: "Was reimt sich auf Tierlunge?",
		description: "Spiele deinen ersten Bierjungen",
		category: "games" as const,
		icon: "🎮",
		targetValue: 1,
		points: 10,
		rarity: "common" as const,
	},
	{
		key: "erstersieg",
		name: "Abgezogen an der Tasse",
		description: "Gewinne dein erstes Spiel",
		category: "games" as const,
		icon: "🏆",
		targetValue: 1,
		points: 15,
		rarity: "common" as const,
	},
	{
		key: "jungerfuchs",
		name: "Junger Fuchs",
		description: "Spiele 10 Spiele",
		category: "games" as const,
		icon: "🎲",
		targetValue: 10,
		points: 50,
		rarity: "uncommon" as const,
	},
	{
		key: "jungaktiver",
		name: "Junger Aktiver",
		description: "Spiele 40 Spiele",
		category: "games" as const,
		icon: "🎲",
		targetValue: 40,
		points: 50,
		rarity: "uncommon" as const,
	},
	{
		key: "winning_streak_3",
		name: "Doppelt auf Spiel",
		description: "Gewinne 3 Spiele in Folge",
		category: "games" as const,
		icon: "🔥",
		targetValue: 3,
		points: 75,
		rarity: "uncommon" as const,
	},
	{
		key: "winning_streak_5",
		name: "Staffettenmeister",
		description: "Gewinne 5 Spiele in Folge",
		category: "games" as const,
		icon: "⚡",
		targetValue: 5,
		points: 150,
		rarity: "rare" as const,
	},
	{
		key: "winning_streak_10",
		name: "Klappen",
		description: "Gewinne 10 Spiele in Folge",
		category: "games" as const,
		icon: "💪",
		targetValue: 10,
		points: 300,
		rarity: "epic" as const,
	},
	{
		key: "champion",
		name: "Tresenchampion",
		description: "Win 100 games total",
		category: "games" as const,
		icon: "🏅",
		targetValue: 100,
		points: 200,
		rarity: "rare" as const,
	},

	// ==================== FINANCIAL ====================
	{
		key: "first_tab",
		name: "Erste Runde auf mich",
		description: "Bestelle dein erstes Bier",
		category: "financial" as const,
		icon: "💳",
		targetValue: 1,
		points: 10,
		rarity: "common" as const,
	},
	{
		key: "big_spender",
		name: "Spender der Getränkekasse",
		description: "Bezahle insgesamt 500€ in Getränken",
		category: "financial" as const,
		icon: "💸",
		targetValue: 500,
		points: 50,
		rarity: "uncommon" as const,
		isSecret: true,
	},
	{
		key: "whale",
		name: "Getränkehai",
		description: "Bezahle insgesamt 5000€ in Getränken",
		category: "financial" as const,
		icon: "🐋",
		targetValue: 5000,
		points: 250,
		rarity: "epic" as const,
		isSecret: true,
	},

	// ==================== TIME ====================
	{
		key: "fruhaufsteher",
		name: "Frühaufsteher",
		description: "Trinke 4 Bier zwischen 5 und 8 Uhr morgens",
		category: "time" as const,
		icon: "🌅",
		targetValue: 1,
		points: 25,
		rarity: "uncommon" as const,
	},
	{
		key: "goldenestunde",
		name: "Goldene Stunde",
		description: "10 Bierbestellungen in einer Stunde",
		category: "time" as const,
		icon: "🕓",
		targetValue: 10,
		isSecret: true,
		points: 50,
		rarity: "rare" as const,
	},
	{
		key: "wocheende",
		name: "Nicht der Pflicht nur zu Genüge",
		description: "Trinke 10 Wocheenden in Folge Bier",
		category: "time" as const,
		icon: "🗓️",
		targetValue: 10,
		points: 75,
		rarity: "rare" as const,
	},
	{
		key: "dedication",
		name: "Dedication",
		description: "Trinke 365 Tage lang Bier",
		category: "time" as const,
		icon: "🏆",
		targetValue: 365,
		isSecret: true,
		points: 500,
		rarity: "legendary" as const,
	},
	{
		key: "berry",
		name: "Berry Staffette",
		description: "Streiche mindestens 4 Bier um 0:00 Uhr ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1,
		isSecret: true,
		points: 100,
		rarity: "rare" as const,
	},
	{
		key: "neujahr",
		name: "Neues Jahr, Neuer Suff",
		description: "Streiche am 1. Januar zwischen 0:00 und 1:00 ein Bier ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 1,
		isSecret: true,
		points: 100,
		rarity: "rare" as const,
	},
	{
		key: "erstermai",
		name: "Tassenkampf statt Klassenkampf",
		description: "Streiche am 1. Mai 10 Bier ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 10,
		isSecret: true,
		points: 100,
		rarity: "rare" as const,
	},
	{
		key: "grundungstag",
		name: "Auf ein ewiges vivat crescat floreat Rhenania!",
		description: "Streiche 10 Bier am 21.02. ab",
		category: "drinking" as const,
		icon: "🌈",
		targetValue: 10,
		isSecret: true,
		points: 100,
		rarity: "rare" as const,
	},

	// ==================== SPECIAL ====================
	{
		key: "willkommen",
		name: "Hausbewohner",
		description: "Erstell deinen Account",
		category: "special" as const,
		icon: "👋",
		targetValue: 1,
		points: 5,
		rarity: "common" as const,
	},
	{
		key: "bild",
		name: "Ahnengalerie",
		description: "Lade ein Bild für dein Profil hoch",
		category: "special" as const,
		icon: "📸",
		targetValue: 1,
		points: 15,
		rarity: "common" as const,
	},
	{
		key: "biergeburtstag",
		name: "Biergeburtstag",
		description: "Nutze die App ein Jahr lang",
		category: "special" as const,
		icon: "🎂",
		targetValue: 1,
		points: 200,
		rarity: "uncommon" as const,
	},
];

export async function seedAchievements() {
	console.log("🏆 Seeding achievements...");

	await db
		.insert(achievements)
		.values(defaultAchievements)
		.onConflictDoNothing();

	console.log(`✅ Seeded ${defaultAchievements.length} achievements`);
}
